-- CityWise Jaipur - Supabase PostgreSQL Database Schema Migration Script
-- Execute this SQL in your Supabase SQL Editor (https://supabase.com/dashboard/project/_/sql)

-- 1. Authorities Table
CREATE TABLE IF NOT EXISTS authorities (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  code TEXT UNIQUE NOT NULL,
  department TEXT NOT NULL,
  contact_email TEXT NOT NULL,
  phone TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Users Table
CREATE TABLE IF NOT EXISTS users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  email TEXT UNIQUE NOT NULL,
  password_hash TEXT NOT NULL,
  role TEXT CHECK(role IN ('CITIZEN', 'AUTHORITY', 'ADMIN')) NOT NULL DEFAULT 'CITIZEN',
  authority_id BIGINT REFERENCES authorities(id) ON DELETE SET NULL,
  phone TEXT,
  avatar_url TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. Wards Table
CREATE TABLE IF NOT EXISTS wards (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  code TEXT UNIQUE NOT NULL,
  boundary_geojson JSONB NOT NULL,
  description TEXT,
  population INT DEFAULT 0,
  area_sq_km NUMERIC(10,2) DEFAULT 0.0,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4. Categories Table
CREATE TABLE IF NOT EXISTS categories (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL UNIQUE,
  code TEXT NOT NULL UNIQUE,
  icon TEXT DEFAULT 'alert-circle',
  description TEXT,
  default_priority TEXT CHECK(default_priority IN ('LOW', 'MEDIUM', 'HIGH', 'CRITICAL')) DEFAULT 'MEDIUM',
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 5. Ward-Authority Routing Table
CREATE TABLE IF NOT EXISTS ward_authorities (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ward_id BIGINT NOT NULL REFERENCES wards(id) ON DELETE CASCADE,
  category_id BIGINT REFERENCES categories(id) ON DELETE CASCADE,
  authority_id BIGINT NOT NULL REFERENCES authorities(id) ON DELETE CASCADE,
  is_primary BOOLEAN DEFAULT TRUE,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  CONSTRAINT unique_ward_category UNIQUE(ward_id, category_id)
);

-- 6. Duplicate Groups / Incident Clusters
CREATE TABLE IF NOT EXISTS duplicate_groups (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  category_id BIGINT REFERENCES categories(id) ON DELETE SET NULL,
  ward_id BIGINT REFERENCES wards(id) ON DELETE SET NULL,
  status TEXT NOT NULL DEFAULT 'ACTIVE',
  primary_issue_id BIGINT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 7. Issues Table
CREATE TABLE IF NOT EXISTS issues (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  description TEXT NOT NULL,
  category_id BIGINT NOT NULL REFERENCES categories(id),
  ward_id BIGINT REFERENCES wards(id),
  authority_id BIGINT REFERENCES authorities(id),
  citizen_id BIGINT NOT NULL REFERENCES users(id),
  status TEXT CHECK(status IN ('REPORTED', 'ASSIGNED', 'IN_PROGRESS', 'RESOLUTION_SUBMITTED', 'VERIFICATION_PENDING', 'CLOSED', 'REOPENED')) NOT NULL DEFAULT 'REPORTED',
  priority TEXT CHECK(priority IN ('LOW', 'MEDIUM', 'HIGH', 'CRITICAL')) NOT NULL DEFAULT 'MEDIUM',
  latitude NUMERIC(10,6) NOT NULL,
  longitude NUMERIC(10,6) NOT NULL,
  address TEXT,
  is_manual_ward BOOLEAN DEFAULT FALSE,
  duplicate_group_id BIGINT REFERENCES duplicate_groups(id) ON DELETE SET NULL,
  resolution_notes TEXT,
  resolved_at TIMESTAMPTZ,
  verified_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 8. Media Table
CREATE TABLE IF NOT EXISTS media (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  issue_id BIGINT NOT NULL REFERENCES issues(id) ON DELETE CASCADE,
  file_url TEXT NOT NULL,
  file_type TEXT CHECK(file_type IN ('IMAGE', 'VIDEO')) NOT NULL DEFAULT 'IMAGE',
  media_stage TEXT CHECK(media_stage IN ('REPORT', 'RESOLUTION')) NOT NULL DEFAULT 'REPORT',
  uploaded_by_id BIGINT NOT NULL REFERENCES users(id),
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 9. Status History Audit Trail Table
CREATE TABLE IF NOT EXISTS status_histories (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  issue_id BIGINT NOT NULL REFERENCES issues(id) ON DELETE CASCADE,
  from_status TEXT,
  to_status TEXT NOT NULL,
  changed_by_id BIGINT NOT NULL REFERENCES users(id),
  remarks TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 10. Supports / Upvotes Table
CREATE TABLE IF NOT EXISTS supports (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  issue_id BIGINT NOT NULL REFERENCES issues(id) ON DELETE CASCADE,
  user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  CONSTRAINT unique_issue_user_support UNIQUE(issue_id, user_id)
);

-- 11. Notifications Table
CREATE TABLE IF NOT EXISTS notifications (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  title TEXT NOT NULL,
  message TEXT NOT NULL,
  type TEXT NOT NULL DEFAULT 'INFO',
  issue_id BIGINT REFERENCES issues(id) ON DELETE CASCADE,
  is_read BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Indexes for performance
CREATE INDEX IF NOT EXISTS idx_issues_citizen ON issues(citizen_id);
CREATE INDEX IF NOT EXISTS idx_issues_authority ON issues(authority_id);
CREATE INDEX IF NOT EXISTS idx_issues_ward ON issues(ward_id);
CREATE INDEX IF NOT EXISTS idx_issues_status ON issues(status);
CREATE INDEX IF NOT EXISTS idx_media_issue ON media(issue_id);
CREATE INDEX IF NOT EXISTS idx_status_history_issue ON status_histories(issue_id);
CREATE INDEX IF NOT EXISTS idx_notifications_user ON notifications(user_id);
